#!/bin/sh

# If block was clicked, toggle mute
if [[ $BLOCK_BUTTON -eq 1 ]]; then
	/home/gabriele/Scripts/myVolumectl toggle
fi

symbol='&#xf357;'
text=''

mute=`amixer get Master | grep -Eo '\[off\]' | wc -l`
if [[ $mute -eq 0 ]]; then
	symbol='&#xf357;'
	color='#f6f02c'
	text=`amixer get Master | grep -E -o '[0-9][0-9]?%'`
else
	text='--'
	#symbol='&#xf358;'
fi

echo $symbol  $text
echo $symbol  $text
echo $color

