#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

percentage_used()
{
	awk  '
	/^MemTotal:/ {
		mem_total=$2
	}
	/^MemFree:/ {
		mem_free=$2
	}
	/^Buffers:/ {
		mem_free+=$2
	}
	/^Cached:/ {
		mem_free+=$2
	}
	END {

	printf("%.0f\n", (mem_total-mem_free)/mem_total*100)
	}
	' /proc/meminfo
}

perc=$(percentage_used)
echo "$perc%"
echo "$perc%"

if [[ $perc -gt 50 ]]; then
	echo "#FFFF00"
elif [[ $perc -gt 75 ]]; then
	echo "#FF0000"
else
	echo "#FFFFFF"
fi

